---
- name: Convert2rhel pre-conversion analysis
  hosts: "{{ centos_lifecycle_environment | default(omit) }}"
  strategy: free
  gather_facts: true
  become: true
  environment:
    CONVERT2RHEL_DISABLE_TELEMETRY: 1
    # CONVERT2RHEL_UNSUPPORTED_INCOMPLETE_ROLLBACK: 1
  vars:
    rhsm_username: ""
    rhsm_password: ""
    rhsm_org: "{{ org_id }}"
    rhsm_activation_key: "{{ rhel_lifecycle_environment }}"
  tasks:
    - name: Verify operating system
      ansible.builtin.assert:
        that:
          - "ansible_distribution == 'CentOS'"
          - "ansible_distribution_major_version | int  == 7"
          - "ansible_distribution_version.split('.')[1] | int >= 9"
        fail_msg: "CentOS 7 minor release must be >= 9"
        success_msg: "CentOS 7 minor release minimum requirement met, continue..."

    - name: Install convert2rhel utility
      ansible.builtin.import_role:
        name: infra.convert2rhel.common

    - name: Pull katello-ca-consumer package from satellite server and place under /usr/share/convert2rhel/subscription-manager
      ansible.builtin.get_url:
        url: https://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        dest: /usr/share/convert2rhel/subscription-manager/katello-ca-consumer-latest.noarch.rpm
        mode: '0440'
        validate_certs: false

    # - name: Download centos-release package locally
    #   ansible.builtin.command: >-
    #     yumdownloader -v --destdir=/root centos-release-7-9.2009.1.el7.centos.x86_64

    - name: Download centos-release package locally
      ansible.builtin.yum:
        name: centos-release
        state: latest
        download_only: true
        download_dir: /root

    - name: Remove centos-release package
      ansible.builtin.command: >-
        rpm -e --nodeps --justdb centos-release

    - name: Generate pre-conversion analysis report
      ansible.builtin.import_role:
        name: infra.convert2rhel.analysis

    - name: Reinstall centos-release package
      ansible.builtin.yum:
        name: /root/centos-release*.rpm
        state: present
...
