---
- name: Convert2rhel conversion
  hosts: "{{ dynamic_inventory_group | default(omit) }}"
  strategy: ansible.builtin.free
  gather_facts: true
  become: true
  environment:
    CONVERT2RHEL_DISABLE_TELEMETRY: 1
    CONVERT2RHEL_UNSUPPORTED_INCOMPLETE_ROLLBACK: 1
  vars:
    rhsm_username: ""
    rhsm_password: ""
    rhsm_org: "{{ org_id }}"
    rhsm_activation_key: "{{ rhel_lifecycle_environment }}"
  tasks:
    - name: Verify operating system
      ansible.builtin.assert:
        that:
          - "ansible_distribution == 'OracleLinux'"
          - "ansible_distribution_major_version | int  == 7"
          - "ansible_distribution_version.split('.')[1] | int >= 9"
        fail_msg: "OracleLinux 7 minor release must be >= 9"
        success_msg: "OracleLinux 7 minor release minimum requirement met, continue..."

    - name: Set delay time via gather_facts
      ansible.builtin.set_fact:
        node_delay_time: "{{ inventory_hostname | regex_replace('^\\D+|\\..*', '') | int *30 }}"

    - name: Include delay before starting conversion
      ansible.builtin.command: |
        python3 -c 'import time;time.sleep({{ node_delay_time }})'
      delegate_to: localhost
      connection: local

    - name: Execute conversion via infra.convert2rhel.convert role
      ansible.builtin.import_role:
        name: infra.convert2rhel.convert

    - name: Generate current repo configuration
      ansible.builtin.command: >-
        subscription-manager repos
      ignore_errors: true

    - name: Update system facts on Satellite
      ansible.builtin.command: >-
        subscription-manager facts --update
      ignore_errors: true
...
