---
- name: Convert2rhel conversion
  hosts: "{{ centos_lifecycle_environment | default(omit) }}"
  strategy: free
  gather_facts: true
  become: true
  environment:
    CONVERT2RHEL_DISABLE_TELEMETRY: 1
    CONVERT2RHEL_UNSUPPORTED_INCOMPLETE_ROLLBACK: 1
  vars:
    rhsm_username: ""
    rhsm_password: ""
    rhsm_org: "{{ org_id }}"
    rhsm_activation_key: "{{ rhel_lifecycle_environment }}"
  tasks:
    - name: Verify operating system
      ansible.builtin.assert:
        that:
          - "ansible_distribution == 'CentOS'"
          - "ansible_distribution_major_version | int  == 7"
          - "ansible_distribution_version.split('.')[1] | int >= 9"
        fail_msg: "CentOS 7 minor release must be >= 9"
        success_msg: "CentOS 7 minor release minimum requirement met, continue..."

    - name: Execute conversion via infra.convert2rhel.convert role
      ansible.builtin.import_role:
        name: infra.convert2rhel.convert

    - name: Update system facts on Satellite
      ansible.builtin.command: >-
        subscription-manager facts --update
      ignore_errors: true
...
