---
- name: Convert2rhel pre-conversion analysis
  hosts: "{{ centos_lifecycle_environment | default(omit) }}"
  strategy: free
  gather_facts: true
  become: true
  environment:
    CONVERT2RHEL_DISABLE_TELEMETRY: 1
    # CONVERT2RHEL_UNSUPPORTED_INCOMPLETE_ROLLBACK: 1
  vars:
    rhsm_username: ""
    rhsm_password: ""
    rhsm_org: "{{ org_id }}"
    rhsm_activation_key: "{{ rhel_lifecycle_environment }}"
    rhsm_activation_key_pre_convert: "{{ centos_lifecycle_environment }}"
  tasks:
    - name: Verify operating system
      ansible.builtin.assert:
        that:
          - "ansible_distribution == 'CentOS'"
          - "ansible_distribution_major_version | int  == 7"
          - "ansible_distribution_version.split('.')[1] | int >= 9"
        fail_msg: "CentOS 7 minor release must be >= 9"
        success_msg: "CentOS 7 minor release minimum requirement met, continue..."

    - name: Install convert2rhel utility
      ansible.builtin.import_role:
        name: infra.convert2rhel.common

    - name: Pull katello-ca-consumer package from satellite server and place under /usr/share/convert2rhel/subscription-manager
      ansible.builtin.get_url:
        url: https://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        dest: /usr/share/convert2rhel/subscription-manager/katello-ca-consumer-latest.noarch.rpm
        mode: '0440'
        validate_certs: false

    - name: Create tempdir for package download
      ansible.builtin.tempfile:
        state: directory
      register: package_dl_tempdir

    - name: Download centos-release package locally
      ansible.builtin.command: >-
        yumdownloader -v --destdir="{{ package_dl_tempdir.path }}" centos-release

    - name: Remove centos-release package
      ansible.builtin.command: >-
        rpm -e --nodeps --justdb centos-release

    - name: Include randomized delay before starting analysis
      ansible.builtin.command: |
        python3 -c 'import time;import random;zzzzz=random.uniform(60.0,120.0);time.sleep(zzzzz);print(zzzzz)'
      delegate_to: localhost
      connection: local

    - name: Generate pre-conversion analysis report
      ansible.builtin.import_role:
        name: infra.convert2rhel.analysis

    - name: Find all rpm files in tempdir "{{ package_dl_tempdir.path }}"
      ansible.builtin.find:
        paths: "{{ package_dl_tempdir.path }}"
        patterns: "*.rpm"
      register: centos_rpm_find
    
    - name: Setting centos_rpm_list from centos_rpm_find
      ansible.builtin.set_fact:
        centos_rpm_list: "{{ centos_rpm_find.files | map(attribute='path') | list }}"

    - name: Installing the rpm files
      ansible.builtin.yum:
        name: "{{ centos_rpm_list }}"
        state: present

    - name: Remove tempdir
      ansible.builtin.file:
        path: "{{ package_dl_tempdir.path }}"
        state: absent

    - name: Get paths to CentOS repos
      ansible.builtin.find:
        paths: /etc/yum.repos.d
        patterns: 'CentOS*.repo'
      register: centos_repos

    - name: Remove CentOS repos that were placed by infra.convert2rhel analysis role
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ centos_repos.files | default([]) }}"
...
