---
- hosts: "{{ HOSTS }}"
  gather_facts: false
  become: true
  tasks:
    - name: Check for presence of satellite.facts
      ansible.builtin.stat:
        path: /etc/rhsm/facts/satellite.facts
      register: satellite_facts_path

    - name: Configure /etc/default/grub
      ansible.builtin.lineinfile:
        dest: /etc/default/grub
        regexp: '^\s*{{ item.var }}\s*=(.*)$'
        line: "{{ item.var }}={{ item.value }}"
        backup: true
      loop:
        - var: GRUB_CMDLINE_LINUX
          value: '"transparent_hugepage=never"'
        - var: GRUB_SERIAL_COMMAND
          value: '"serial --speed=115200"'
        - var: GRUB_TERMINAL
          value: '"serial console"'
      when: satellite_facts_path.stat.exists
#      notify: Rebuild grub.cfg

#  handlers:
#    - name: "Rebuild grub.cfg"
#      ansible.builtin.command: >-
#        grub2-mkconfig -o /boot/grub2/grub.cfg
...
