---
- hosts: "{{ HOSTS }}"
  gather_facts: false
  become: true
  tasks:
    - name: Check for presence of satellite.facts
      ansible.builtin.stat:
        path: /etc/rhsm/facts/satellite.facts
      register: satellite_facts_path

    - name: Disable transparent hugepages
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX="((?:(?!transparent_hugepage=never).)*?)"$'
        line: 'GRUB_CMDLINE_LINUX="\1 transparent_hugepage=never"'
        backup: true
        backrefs: true
      when: satellite_facts_path.stat.exists
#      notify: Rebuild grub.cfg

#  handlers:
#    - name: "Rebuild grub.cfg"
#      ansible.builtin.command: >-
#        grub2-mkconfig -o /boot/grub2/grub.cfg
...
