---
- name: Extend logical volume
  hosts: "{{ HOSTS is defined | ternary(HOSTS, PREFIX|default('')+'*') }}"
  strategy: free
  gather_facts: true
  become: true
  tasks:
    - name: Extend logical volume 
      community.general.lvol:
        vg: "{{ volume_group_name }}"
        lv: "{{ logical_volume_name }}"
        size: +"{{ extend_logical_volume_mb }}"M
...
