---
- hosts: all
  become: true
  tasks:
  - name: Create gpg key directory for importing keys
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    with_items:
      - /etc/pki/rpm-gpg/import

  - name: Pull down Oracle Linux 7 GPG key
    ansible.builtin.get_url:
      url: https://yum.oracle.com/RPM-GPG-KEY-oracle-ol7
      dest: /etc/pki/rpm-gpg/import/RPM-GPG-KEY-oracle-ol7
      mode: '0440'
    register: getoracle7gpgkey
    until: getoracle7gpgkey is succeeded

  - name: hammer org list
    ansible.builtin.command: >-
      hammer --output json organization list
    register: hammer_org_list_result
    ignore_errors: true

  - name: set the Organization Id from specific org selection via "{{ organization }}" variable and .Id
    set_fact: sat_org_id={{ hammer_org_list_result.stdout | from_json | json_query(my_query) }}
    vars:
      my_query: "[?Name=='{{ organization }}'].Id"

  - name: What is the Org Id? 
    ansible.builtin.debug:
      msg: "The Org Id selected is: {{ sat_org_id[0] }}"

  - name: hammer create RPM-GPG-KEY-oracle-ol7 key
    ansible.builtin.command: >-
      hammer content-credentials create --organization-id {{ sat_org_id[0] }}
      --path "/etc/pki/rpm-gpg/import/RPM-GPG-KEY-oracle-ol7"
      --name "RPM-GPG-KEY-oracle-ol7"
      --content-type gpg_key
    register: hammer_oracle_gpgkey_result
    ignore_errors: true

  - name: RPM-GPG-KEY-oracle-ol7 key creation output 
    ansible.builtin.debug:
      msg: "{{ hammer_oracle_gpgkey_result.stdout }}"
...
