---
# https://devpress.csdn.net/cicd/62ec1d2689d9027116a10320.html
- name: Satellite manifest refresh workloads Task Group
  block:
    - name: Force Satellite production.log log rotation
      ansible.builtin.shell: logrotate -v -f /etc/logrotate.d/foreman
      become: true

    - name: Increment retry count
      ansible.builtin.set_fact:
        manifest_refresh_retry_count: "{{ manifest_refresh_retry_count | int + 1 }}"

    - name: Resume failed Satellite tasks after each failed attempt
      ansible.builtin.include_tasks: satellite_hammer_task_resume.yml
      when: manifest_refresh_retry_count | int != 1

    - name: refresh manifest
      redhat.satellite.subscription_manifest:
        organization: "Default Organization"
        state: refreshed
      async: "{{ refresh_timeout }}"
      poll: 0
      register: refresh_async
      vars:
        ansible_connection: local

    - name: >
        Watch Satellite production.log until ManifestRefresh result ==> success appears before continuing...
      ansible.builtin.wait_for:
        path: "/var/log/foreman/production.log"
        search_regex: "^.*ManifestRefresh.*state\ changed.*\ stopped\ \ result.*\ success"
        timeout: "{{ refresh_timeout }}"
        sleep: 10
      become: true

  rescue:
    - ansible.builtin.fail:
        msg: Maximum retries of grouped tasks reached
      when: manifest_refresh_retry_count | int == 4

    - ansible.builtin.debug:
        msg: "Satellite manifest refresh Task Group failed, retry count: {{ manifest_refresh_retry_count }}"

    - ansible.builtin.include_tasks: satellite_manifest_subtasks_retry.yml
...
