---
- name: Import manifest refresh tempfile init playbook
  ansible.builtin.import_playbook: satellite_manifest_refresh_tempfile_init.yml

- name: Import manifest refresh role execution playbook
  ansible.builtin.import_playbook: satellite_manifest_refresh_execute_role.yml

- name: Import manifest refresh watch tempfile playbook
  ansible.builtin.import_playbook: satellite_manifest_refresh_watch_tempfile.yml
...
