---
- name: Satellite manifest refresh odyssey
  hosts: "{{ HOSTS | default('satellite.example.com') }}"
  vars:
    refresh_timeout: 14400
  tasks:
    - name: Satellite manifest refresh workloads Task Group
      ansible.builtin.include_tasks: satellite_manifest_subtasks_init.yml
...
