---
- name: Satellite Configuration as Code automation
  hosts: "{{ HOSTS | default('satellite.example.com') }}"
  connection: local
  gather_facts: false
  tasks:
    - name: Satellite deployment instrumentation
      ansible.builtin.uri:
        url: https://docs.google.com/forms/d/e/1FAIpQLSdIZ77YpETjEfGOoYlXtMnQiU-6M7QFlb2hJA4ujo25QYb2jw/formResponse
        method: POST
        body: "ifq&entry.1569353616=smart_mgmt &entry.498055740={{ lookup('ansible.builtin.env', 'AWX_HOST') }}&sumbit=Submit"
      ignore_errors: true

    - name: Check satellite status
      redhat.satellite.status_info:
        validate_certs: false

- name: Satellite disconnected mode
  hosts: "{{ HOSTS | default('satellite.example.com') }}"
  become: true
- name: Satellite disconnected mode
  import_playbook: satellite_disconnected_mode.yml
  vars:
    disconnected_mode: "false"
  when: refresh_satellite_manifest

- name: Satellite set bulk_load_size
  import_playbook: satellite_set_bulk_load_size.yml
  vars:
    bulk_load_size: 1000

- name: Satellite CaC subtasks with dynamic retries
  hosts: "{{ HOSTS | default('satellite.example.com') }}"
  connection: local
  gather_facts: false
  tasks:
    - name: Satellite CaC workload Task Groups
      ansible.builtin.include_tasks: setup_satellite_infra_subtasks.yml

- hosts: "{{ HOSTS | default('satellite.example.com') }}"
  vars:
    refresh_satellite_manifest: false
    refresh_timeout: 14400
  tasks:
    - name: Satellite manifest refresh workload Task Groups
      ansible.builtin.include_tasks: satellite_manifest_subtasks_init.yml
...
