---
- name: Update OS and reboot
  hosts: "{{ dynamic_inventory_group | default(omit) }}"
  gather_facts: false
  become: true
  tasks:
    - name: Wait for connection...
      ansible.builtin.wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300

    - name: Update OS to latest packages available
      ansible.builtin.yum:
        name: '*'
        state: latest # noqa package-latest

    - name: Reboot server
      ansible.builtin.reboot:
      register: reboot_result

    - name: Wait for connection...
      ansible.builtin.wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
...
